### ISSUE TITLE
关于在单张肖像动画化试验中所使用的image2latent的问题。

### ISSUE THREAD

**Issue by Xu-Zirui** [bytedance/pv3d#2]
非常感谢作者的工作，请问作者可否提供在单张肖像动画化中所使用的image2latent的模型权重？
十分感谢

**Comment by zcxu-eric** [comment]
Hello, thanks for your interest.

We didn't train any general encoder for the input image. Instead, we follow the conventional GAN inversion method using single image reconstruction. 

A similar script can be found [here](https://github.com/rosinality/stylegan2-pytorch/blob/master/projector.py).
